apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: opsera-enterpriseapp-vote-dev
labels:
  - pairs:
      environment: dev
    includeSelectors: false
images:
  - name: PLACEHOLDER_ECR_URI_VOTE
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/enterpriseapp-vote-vote
    newTag: "1cdd89d-20260216023646"
  - name: PLACEHOLDER_ECR_URI_RESULT
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/enterpriseapp-vote-result
    newTag: "4c7aa60-20260216031723"
  - name: PLACEHOLDER_ECR_URI_WORKER
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/enterpriseapp-vote-worker
    newTag: "b24d491-20260216022745"
patches:
  - target:
      kind: ConfigMap
      name: enterpriseapp-vote-config
    patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: enterpriseapp-vote-config
      data:
        REDIS_HOST: "enterpriseapp-vote-dev.2muj25.0001.usw2.cache.amazonaws.com"
        DB_HOST: "enterpriseapp-vote-dev.chwgk42cofpp.us-west-2.rds.amazonaws.com"
  - target:
      kind: Service
      name: redis
    patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: redis
      spec:
        externalName: enterpriseapp-vote-dev.2muj25.0001.usw2.cache.amazonaws.com
  - target:
      kind: Service
      name: db
    patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: db
      spec:
        externalName: enterpriseapp-vote-dev.chwgk42cofpp.us-west-2.rds.amazonaws.com
