apiVersion: v1
kind: ConfigMap
metadata:
  name: enterpriseapp-vote-config
  labels:
    app: enterpriseapp-vote
    managed-by: opsera-c2c
data:
  REDIS_HOST: "redis.local"
  DB_HOST: "db.local"
  OPTION_A: "Cats"
  OPTION_B: "Dogs"
