apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - redis-external.yaml
  - db-external.yaml
  - vote-deployment.yaml
  - vote-service.yaml
  - result-deployment.yaml
  - result-service.yaml
  - worker-deployment.yaml
  - ingress.yaml

labels:
  - pairs:
      app: enterpriseapp-vote
      tenant: opsera
      managed-by: opsera-c2c
    includeSelectors: false
